import { GoogleGenAI, Modality } from "@google/genai";
import * as fs from 'fs';
import * as path from 'path';

async function testLiveAudio() {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_KEY_3 });
    const pcmPath = path.join(process.cwd(), "question.wav");
    const outPath = path.join(process.cwd(), "response.pcm");

    // Read the WAV file generated by PowerShell
    const wavBuffer = fs.readFileSync(pcmPath);
    // Strip the 44-byte WAV header to get raw PCM data (16kHz, 16-bit Mono)
    const pcmBuffer = wavBuffer.subarray(44);
    const pcmBase64 = pcmBuffer.toString('base64');

    console.log("Connecting to Gemini Live API...");
    try {
        const session = await ai.live.connect({
            model: "gemini-2.5-flash-native-audio-preview-12-2025",
            config: {
                systemInstruction: {
                    parts: [{ text: "You are a helpful AI assistant." }],
                },
                responseModalities: [Modality.AUDIO],
                speechConfig: {
                    voiceConfig: {
                        prebuiltVoiceConfig: {
                            voiceName: "Aoede",
                        },
                    },
                },
            },
            callbacks: {
                onmessage: (msg) => {
                    // Check for Audio Content natively
                    if (msg.serverContent?.modelTurn?.parts) {
                        for (const part of msg.serverContent.modelTurn.parts) {
                            if (part.inlineData?.data) {
                                console.log(`Received Audio Chunk: ${part.inlineData.data.substring(0, 50)}...`);
                                // Append raw base64 decoded data to our output file
                                const audioBuf = Buffer.from(part.inlineData.data, 'base64');
                                fs.appendFileSync(outPath, audioBuf);
                            }
                        }
                    }
                    if (msg.serverContent?.turnComplete) {
                        console.log("Turn Complete. Audio saved to response.pcm!");
                        session.close();
                    }
                },
                onclose: (e) => console.log(`Closed: code=${e.code}, reason='${e.reason}'`),
            }
        });
        console.log("Connected successfully! Sending actual audio question...");

        // Clear previous response
        if (fs.existsSync(outPath)) fs.unlinkSync(outPath);

        // Send the audio buffer
        session.sendRealtimeInput({
            audio: {
                mimeType: "audio/pcm;rate=16000",
                data: pcmBase64
            }
        });

        // Keep process alive long enough to receive the full audio response
        await new Promise(r => setTimeout(r, 15000));
        console.log("Timeout reached. Closing session...");
        try { session.close(); } catch (e) { }

    } catch (e) {
        console.error("Connection failed:", e);
    }
}

testLiveAudio();
